version: '3'

services:
  app-book:
    image: app-book:v8
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080"

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"